version: '3.3'

services:

  db:
    image: mysql:8.0.31
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: someghost 
      MYSQL_DATABASE: ghost 
      MYSQL_USER: ghost 
      MYSQL_PASSWORD: ghost


  ghost:
    depends_on:
      - db
    image: ghost:4-alpine
    ports:
      - 8080:2368
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ghost
      WORDPRESS_DB_PASSWORD: ghost
      WORDPRESS_DB_NAME: ghost
      url: http://localhost:9000
volumes:
  db_data: {}